### PR TITLE
Transparent FeedForwardPolicy and improved VecEnvs

### PR DESCRIPTION
**Pull request by kantneel**
Two disjoint sets of features: 
- FeedForwardPolicy now exposes instance variables for hidden layer size and feedforward activations which can be used in Transparent environments and policies. 
- VecEnv get_attr, set_attr and env_method have been improved to all support indices and also refactored into abstractmethods.

### CODE REVIEW

**Comment by AdamGleave** [comment]
This is a little confusing as it includes change from `env_method` as well as additional changes. I'm going to wait until we merge the `env_method` PR into Stable Baselines, so I can just look at the actual diff.

**Comment by AdamGleave** [comment]
I've updated `adv-policies` to track Stable Baselines, including your merged PR. There are some merge conflicts, can you resolve them and I'll take a look at what remains of this PR (the `FeedForwardPolicy` changes)?

**Comment by kantneel** [comment]
Resolved the merge conflicts.

**Review by AdamGleave — APPROVED** [review]
LGTM

**Pull request merged**
