### PR TITLE
added __getattr__ to VecEnvWrapper

### PR DESCRIPTION
**Pull request by kantneel**
See https://github.com/hill-a/stable-baselines/issues/274

### CODE REVIEW

**Comment by AdamGleave** [comment]
Why do we have two PRs for the same feature, one here and one on Stable Baselines?

**Comment by kantneel** [comment]
Wasn't sure if/when it would be closed on stable baselines, and perhaps we would ultimately have a different opinion on it for the purposes of this repo than for stable baselines in general. We can remove this one if you'd like.

**Comment by AdamGleave** [comment]
OK, fair enough, we can leave it open although think we can get it merged
into Stable Baselines soon. It's confusing since adv-policies is a little
out of track of master so the diff is much bigger than it should, but
that's fixable.

**Comment by AdamGleave** [comment]
Closing as we merged in Stable Baselines

**Pull request closed without merging**
